version: '{build}'
os: Windows Server 2012
environment:
    SBT_OPTS: -Dfile.encoding=UTF8
    JAVA_OPTS: -Dfile.encoding=UTF8
install:
    - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt""" -y
    - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
    - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
    - sbt ++$scala_version$ clean compile    
cache:
    - C:\sbt\
    - C:\Users\appveyor\.m2
    - C:\Users\appveyor\.sbt
    - C:\Users\appveyor\.ivy2
